name: Run Python Script Every Minute

on:
  schedule:
    - cron: "* * * * *"  # Every minute

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure this step is properly installing the dependencies

      - name: Verify dependencies
        run: |
          pip show requests  # Verifies that the 'requests' module is installed

      - name: Run the script
        run: python lvlchk.py  # Runs the Python script
